name: publish 

on:
  push:
    branches:
      - 'dev'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: current
      - uses: actions/checkout@v4
        with:
          ref: main 
          path: main
      - name: Setup Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          cd current
          python -m pip install --upgrade pip -r requirements.txt
      - name: Update analysis notebook
        run: |
          cd current
          if [ -f *.ipynb ]; then
            python -m pip install jupyter nbconvert nbformat
            jupyter nbconvert --to notebook --execute *.ipynb --clear-output
          fi
          mv *.ipynb ../main/
          mv *.py ../main/
          mv *.md ../main/
          mv data ../main/ || echo "not existing file" 
      - name: Commit updated notebook
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions 
          message: "Update main Notebook"
          add: "."
          new_branch: main 
          cwd: "./main"
 