name: publish 

on:
  push:
    branches:
      - 'dev'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: current
      - uses: actions/checkout@v4
        with:
          ref: main 
          path: main
      - name: Setup Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          cd current
          python -m pip install --upgrade pip -r requirements.txt
          python -m spacy download en_core_web_md
      - name: Update analysis notebook
        run: |
          cd current
          for f in *.ipynb ; do
            python -m pip install jupyter nbconvert nbformat
            jupyter nbconvert --to notebook --execute *.ipynb --clear-output
            mv *.ipynb ../main/
            break
          done
      - name: Move files
        if: always()
        run: |
          cd current
          mv *.py ../main/ || echo "not existing file" 
          mv *.md ../main/ || echo "not existing file"
          mkdir ../main/data || echo "dir exist"
          mkdir ../main/utils || echo "dir exist"
          mv data/* ../main/data/ || echo "not existing directory"  
          mv utils/* ../main/utils/ || echo "not existing directory"
      - name: Commit updated notebook
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions 
          message: "Update main Notebook"
          add: "./*"
          new_branch: main 
          cwd: "./main"
 