name: strip-and-push 

on:
  push:
    branches-ignore:
      - '*-clean' 
      - 'dev'
      - 'main'

jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
        with:
          path: current
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}-clean
          path: clean
      - name: Setup git user
        if: always()
        run: |
            cd current
            git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
            git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
      - name: Setup Python 
        if: always()
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Strip notebook
        if: always()
        run: |
          cd current
          for f in *.ipynb ; do
            python -m pip install jupyter nbconvert nbformat
            jupyter nbconvert --clear-output --inplace *.ipynb
            cp *.ipynb ../clean
            break
          done
      - name: Copy files
        if: always()
        run: |
          cd current
          cp *.py ../clean || echo "not existing file" 
          cp *.md ../clean || echo "not existing file" 
          cp -r data ../clean/ || echo "not existing directory"
          cp -r utils ../clean/ || echo "not existing directory"
      - name: Empty commit
        if: failure()
        run: |
          clean_branch_name="${{ steps.extract_branch.outputs.branch }}-clean"
          cd current
          git checkout -b ${clean_branch_name}
          git commit --allow-empty -m "init clean"
          git push origin ${clean_branch_name}
      - name: commit updated notebook (old branch)
        if: success()
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions 
          message: "Update stripped Notebook"
          add: "./*"
          new_branch: ${{ steps.extract_branch.outputs.branch }}-clean
          cwd: "./clean"
      - name: commit updated notebook (new branch)
        if: failure()
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions 
          message: "Update stripped Notebook"
          add: "./*"
          new_branch: ${{ steps.extract_branch.outputs.branch }}-clean
          cwd: "./current"